INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Adelaide Zoological Gardens', 'Adelaide Zoo', 'AU', 'South Australia', 'Adelaide', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Zoo of Bauru', 'Bauru Zoo', 'BRA', 'São Paulo', 'Bauru', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'City of Belfast Zoo', 'Belfast Zoo', 'UK', 'Belfast', NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Zoological Garden of Brasilia', 'Brasilia Zoo', 'BRA', 'Distrito Federal', 'Brasilia', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Bristol Zoo', 'Bristol Zoo', 'UK', 'Clifton', 'Bristol', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Buri Wild', 'Buri Wild', 'BRA', 'São Paulo', 'Buri', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Central Park Wildlife Center', 'Central Pk NY', 'USA', 'New York', 'New York', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'North of England Zoo Society', 'Chester Zoo', 'UK', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Fort Worth Zoological Park', 'Fortworth Zoo', 'USA', 'Texas', NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Durrell Wildlife Conservation Trust', 'Jersey Zoo', 'UK', 'Channel Islands', NULL, 1);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Krefelder Zoo', 'Krefelder Zoo', 'GER', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'La Palmyre Zoo', 'La Palmmyre Zoo', 'FRA', 'Royan', NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Lisbon Zoo', 'Lisbon Zoo', 'POR', 'Lisboa', NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Morro do Diabo Ecological Park', 'PEMD Wild', 'BRA', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'MIDDLE GOBI  ', 'M Gobi', 'MON', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Zoologischer Garten Magdeburg', 'Magdeburg Zoo', 'GER', 'Sachsen-anhalt', NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'The Wildlife Conservation Society', 'Bronx NY', 'USA', 'New York', 'New York', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Private Collection', 'Private Collection', 'BRA', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Prospect Park Wildlife Center', 'Prospect NY', 'USA', 'New York', 'New York', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Ribeirao Bonito Farm', 'FRBonito', 'BRA', 'São Paulo ', NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Rio de Janeiro Primatology Center', 'CPRJ', 'BRA', 'Rio de Janeiro', 'Rio de Janeiro', 2);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Sao Paulo Zoological Park Foundation', 'FPZSP', 'BRA', 'São Paulo', 'São Paulo', 3);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Quinzinho de Barros Zoological Park', 'PZQB', 'BRA', 'Sao Paulo', 'Sorocaba', NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Sao Carlos Ecological Park', 'PESC', 'BRA', 'Sao Paulo', 'São Carlos', 4);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Unknown Location', 'Unk 1', 'BRA', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Brazil', 'Unk 2', 'BRA', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'WILD', 'Unk Wild', 'BRA', NULL, NULL, NULL);
INSERT INTO `institute` (`id`, `name`, `abbreviation`, `country`, `state`, `city`, `priority`) VALUES (NULL, 'Belo Horizonte Zoo', 'BH Zoo', 'BRA', 'Minas Gerais', 'Belo Horizonte', NULL);
