INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0335', 'IPE Santa Maria', 'FZSM', '1', '-52,296886', '-22,236353');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0336', 'IPE Santa Maria', 'FZSM', '1', '-52,296886', '-22,236353');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0337', 'IPE Santa Maria', 'FZSM', '2', '-52,308', '-22,231806');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0338', 'IPE Santa Maria', 'FZSM', '2', '-52,308', '-22,231806');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0339', 'IPE Santa Maria', 'FZSM', '2', '-52,308', '-22,231806');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0340', 'IPE Santa Maria', 'FZSM', '2', '-52,308', '-22,231806');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0341', 'IPE Santa Maria', 'FZSM', '2', '-52,308', '-22,231806');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0342', 'IPE Santa Maria', 'FZSM', '2', '-52,308', '-22,231806');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0343', 'IPE Santa Maria', 'FZSM', '2', '-52,308', '-22,231806');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0344', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,182452', '-22,612203');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0345', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,182452', '-22,612203');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0346', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,182452', '-22,612203');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0347', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,182452', '-22,612203');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0348', 'Guarei fragments', 'Guareí', 'Guareí (Camargo)', '-48,241836', '-23,416572');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0349', 'Guarei fragments', 'Guareí', 'Guareí (Camargo)', '-48,237983', '-23,417975');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0350', 'Guarei fragments', 'Guareí', 'Guareí (Camargo)', '-48,237983', '-23,417975');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0351', 'Guarei fragments', 'Guareí', 'Guareí (Camargo)', '-48,237983', '-23,417975');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0352', 'Guarei fragments', 'Guareí', 'Guareí (Camargo)', '-48,237983', '-23,417975');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0353', 'Guarei fragments', 'Guareí', 'Guareí (Camargo)', '-48,237983', '-23,417975');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0430', 'BLT Ecological Station', 'PB', 'Ponte Branca', '-52,508509', '-22,425176');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0431', 'BLT Ecological Station', 'PB', 'Ponte Branca', '-52,508509', '-22,425176');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0432', 'BLT Ecological Station', 'PB', 'Ponte Branca', '-52,508509', '-22,425176');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0433', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,174668', '-22,617833');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0434', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,174668', '-22,617833');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0435', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,174668', '-22,617833');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0436', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', '-52,174668', '-22,617833');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0437', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', 'None', 'None');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0438', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', 'None', 'None');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0439', 'Morro do Diabo State Park', 'PEMD', 'PEMD Sede', 'None', 'None');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0440', 'Guareí', 'Guareí', 'Guareí 02 (Camargo)', 'None', 'None');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM_0441', 'Guareí', 'Guareí', 'Guareí 01 (Camargo)', 'None', 'None');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0001', 'Flona Capão Bonito', 'FNCP', '1', '-48,532665', '-23,88868');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0002', 'Flona Capão Bonito', 'FNCP', '1', '-48,532665', '-23,88868');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0003', 'Flona Capão Bonito', 'FNCP', '1', '-48,532665', '-23,88868');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0004', 'Flona Capão Bonito', 'FNCP', '1', '-48,532665', '-23,88868');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0005', 'Flona Capão Bonito', 'FNCP', '1', '-48,532665', '-23,88868');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0006', 'Flona Capão Bonito', 'FNCP', '2', '-48,532665', '-23,901291');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0007', 'Flona Capão Bonito', 'FNCP', '2', '-48,532665', '-23,901291');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0008', 'Flona Capão Bonito', 'FNCP', '2', '-48,532665', '-23,901291');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0009', 'Flona Capão Bonito', 'FNCP', '2', '-48,532665', '-23,901291');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0010', 'Flona Capão Bonito', 'FNCP', '2', '-48,532665', '-23,901291');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0213', 'Riparian forest of Guarei River', 'Guareí', 'Guareí - bridge', '-48,208116', '-23,376237');
INSERT INTO `wild_location` (`id_individual`, `fragment`, `pop`, `group`, `longitude`, `latitude`) VALUES ('MAM-0214', 'Buri', '', 'None', 'None', 'None');
