INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Lchu1','Microsatellite', 'GALBUSERA; GILLEMOT, 2008', 'GCTCAGGTGTTATTTATGTCCAAA','GTTTCTTGCAACTATCTTGCATGTTCTGC');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Lchu6','Microsatellite', 'GALBUSERA; GILLEMOT, 2008', 'GCCTTAATTAGCACCAGAACC','GTTTCTTACCACTCCAAGCCTTCAGTA');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Lchu7','Microsatellite', 'GALBUSERA; GILLEMOT, 2008', 'TCTCATTTCTTCTCATGGACTC','GTTTCTTCTTGACTCACAGCATGACCT');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Lchu8','Microsatellite', 'GALBUSERA; GILLEMOT, 2008', 'CACGGCAATGTGGGAATAA','GTTTCTTTTCAGTAGTTGGGACTGGGATAA');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('LrP2BH6','Microsatellite', 'GRATIVOL; BALLOU; FLEISCHER, 2001', 'TCTGTTTGAATCCCCAGTCC','GCAGTCCCTCAAGGTTTTCT');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('LrP5BE6','Microsatellite', 'GRATIVOL; BALLOU; FLEISCHER, 2001', 'TGTGCATGCTTGCCTGTGTC','ATCTCACTGGACCCACCT');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon2','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'CTGCTTCTTGTTCCACTTCTTCTC','GTTTGGGTGGTTGCCAAG');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon3C20','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'CTGTATGTGATCGCTTTTACCTG','AAGGCAATCTAACTAATCAACACTC');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon11c72','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'AGGATTACAGGTGCCCAC','TTGCATATTGTGTTCAACTTC');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon15C85','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'CTGATCCTTGAAGCAGCATTG','GGTTAAAGGGGTTCGTTCTGTG');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon21C75','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'CAGTTGAGGGAACAGGAATTA','CACTGCACTGACAGAGCAAG');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon30C73','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'GGACCTGATTGAAGCAGTC','TTCCCTGAGAATCTAATGGAG');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon31C97','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'TGGTCCAGAGAAATGATGTC','GTAATTCCTTGGATTTATGCC');
INSERT INTO `locus` (`locus`, `type`, `reference`, `forward`, `reverse`) VALUES ('Leon35c42','Microsatellite', 'PEREZ-SWEENEY et al., 2005', 'GTGGAAAGGTTTCAGAATATC','TGCAGTTGTCCACACTTTA');
